apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: ecokids-worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: ecokids-worker
  template:
    metadata:
      labels:
        app: ecokids-worker
    spec:
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secrets
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "20"] # Give BullMQ time to finish active jobs
