apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ecokids-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ecokids-worker
