apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # Base64 encoded values injected via CI/CD or External Secrets Operator
  MONGODB_URI: {{ .Values.secrets.mongodbUri | b64enc | quote }}
  REDIS_URI: {{ .Values.secrets.redisUri | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  CLOUDINARY_URL: {{ .Values.secrets.cloudinaryUrl | b64enc | quote }}
