#!/usr/bin/env node
const mongoose = require('mongoose');
require('dotenv').config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/ecokids';

const categories = ['climate', 'biodiversity', 'water', 'waste', 'energy'];
const grades = ['6-8', '9-10', '11-12'];

const lessons = [
    // Climate (10)
    { title: 'What is Climate Change?', titleHi: 'जलवायु परिवर्तन क्या है?', category: 'climate', grade: '6-8', ncert: ['EVS-6.1'], quiz: ['What gas traps heat?|CO2|O2|N2|H2|0', 'Global warming is caused by?|Greenhouse gases|Ozone|Rainfall|Wind|0', 'Which is a renewable energy?|Solar|Coal|Diesel|Kerosene|0', 'Ice caps are melting due to?|Rising temperatures|Earthquakes|Floods|Wind|0', 'What can reduce carbon footprint?|Cycling|Driving alone|Flying|Burning trash|0'] },
    { title: 'The Greenhouse Effect', titleHi: 'ग्रीनहाउस प्रभाव', category: 'climate', grade: '6-8', ncert: ['EVS-6.2'], quiz: ['Greenhouse gases include?|Methane|Oxygen|Argon|Helium|0', 'What traps solar heat?|Atmosphere|Ocean|Soil|Rock|0', 'Earth without greenhouse effect would be?|Frozen|Hot|Same|Windy|0', 'CO2 comes from?|Burning fossil fuels|Photosynthesis|Rain|Snow|0', 'Plants help by?|Absorbing CO2|Releasing CO2|Nothing|Blocking sun|0'] },
    { title: 'Carbon Footprint Calculator', titleHi: 'कार्बन फुटप्रिंट कैलकुलेटर', category: 'climate', grade: '9-10', ncert: ['Sci-10.15'], quiz: ['Biggest personal carbon source?|Transportation|Reading|Sleeping|Walking|0', '1 flight = how many trees/year?|Several|Zero|Half|One|0', 'LED vs CFL saves?|More energy|Less energy|Same|None|0', 'Meat production causes?|High emissions|Low emissions|No emissions|Negative|0', 'Best transport choice?|Public transit|Private car|Helicopter|Yacht|0'] },
    { title: 'Renewable Energy Sources', titleHi: 'नवीकरणीय ऊर्जा स्रोत', category: 'climate', grade: '9-10', ncert: ['Sci-10.14'], quiz: ['Solar energy comes from?|Sun|Moon|Stars|Wind|0', 'Wind turbines convert?|Kinetic to electric|Heat to light|Sound to heat|Light to heat|0', 'Hydropower uses?|Water flow|Wind|Sunlight|Coal|0', 'Biomass is from?|Organic matter|Rocks|Metal|Plastic|0', 'Geothermal energy is from?|Earth heat|Ocean waves|Rain|Snow|0'] },
    { title: 'India\'s Climate Action Plan', titleHi: 'भारत की जलवायु कार्य योजना', category: 'climate', grade: '11-12', ncert: ['Geo-12.7'], quiz: ['India\'s climate target year?|2070|2030|2050|2025|0', 'NAPCC stands for?|National Action Plan on Climate Change|None|National Air Policy|National Agriculture Plan|0', 'India\'s solar mission target?|500GW by 2030|100GW|50GW|10GW|0', 'COP stands for?|Conference of Parties|Council of People|Committee of Planning|Circle of Protection|0', 'Paris Agreement goal?|Limit warming to 1.5C|Reduce rain|Increase wind|Stop earthquakes|0'] },
    { title: 'Weather vs Climate', titleHi: 'मौसम बनाम जलवायु', category: 'climate', grade: '6-8', ncert: ['EVS-6.3'], quiz: ['Weather changes?|Daily|Never|Yearly|Century|0', 'Climate is measured over?|30+ years|1 day|1 week|1 month|0', 'Meteorologists study?|Weather|Rocks|Oceans|Space|0', 'Thermometer measures?|Temperature|Wind|Rain|Clouds|0', 'Seasons are caused by?|Earth tilt|Moon|Sun size|Stars|0'] },
    { title: 'Extreme Weather Events', titleHi: 'चरम मौसम की घटनाएं', category: 'climate', grade: '9-10', ncert: ['Sci-10.16'], quiz: ['Cyclones form over?|Warm oceans|Mountains|Deserts|Forests|0', 'Floods are caused by?|Heavy rainfall|Drought|Cold|Wind|0', 'Heatwaves are?|Prolonged hot periods|Cold snaps|Rainy days|Snowy|0', 'Droughts affect?|Agriculture|Nothing|Buildings|Roads|0', 'Early warning systems help?|Save lives|Cause disaster|Nothing|Increase harm|0'] },
    { title: 'Ozone Layer Protection', titleHi: 'ओजोन परत संरक्षण', category: 'climate', grade: '9-10', ncert: ['Sci-10.15.2'], quiz: ['Ozone layer blocks?|UV rays|Visible light|Radio waves|Sound|0', 'CFCs damage?|Ozone|Water|Soil|Air|0', 'Montreal Protocol bans?|CFCs|CO2|Methane|Nitrogen|0', 'Ozone hole is over?|Antarctica|India|Africa|America|0', 'Ozone is made of?|3 oxygen atoms|2 oxygen|Carbon|Nitrogen|0'] },
    { title: 'Urban Heat Islands', titleHi: 'शहरी ऊष्मा द्वीप', category: 'climate', grade: '11-12', ncert: ['Geo-12.8'], quiz: ['Cities are hotter due to?|Concrete and asphalt|Trees|Water|Grass|0', 'Green roofs help by?|Cooling buildings|Heating|Nothing|Blocking rain|0', 'Albedo effect relates to?|Surface reflectivity|Sound|Smell|Taste|0', 'Best urban cooling strategy?|Tree planting|More concrete|More cars|Less water|0', 'Heat islands increase?|Energy consumption|Reading|Walking|Sleeping|0'] },
    { title: 'Climate Justice', titleHi: 'जलवायु न्याय', category: 'climate', grade: '11-12', ncert: ['Geo-12.9'], quiz: ['Who is most affected by climate change?|Vulnerable communities|Rich nations|No one|Animals only|0', 'Climate justice means?|Fair distribution of impacts|Ignoring climate|More pollution|Less action|0', 'Developing nations need?|Support and funding|Nothing|More emissions|Less food|0', 'IPCC provides?|Scientific assessments|Weather forecasts|Sports scores|Entertainment|0', 'Adaptation means?|Adjusting to changes|Ignoring changes|Causing changes|Reversing time|0'] },
    // Biodiversity (10)
    { title: 'What is Biodiversity?', titleHi: 'जैव विविधता क्या है?', category: 'biodiversity', grade: '6-8', ncert: ['EVS-6.5'], quiz: ['Biodiversity means?|Variety of life|Single species|Only plants|Only animals|0', 'Hotspot means?|High species + threat|Cold place|Empty land|Desert|0', 'India has how many biodiversity hotspots?|4|1|2|10|0', 'Endemic species are found?|Only in one area|Everywhere|Nowhere|In space|0', 'Conservation protects?|Species and habitats|Buildings|Roads|Machines|0'] },
    { title: 'Forests of India', titleHi: 'भारत के वन', category: 'biodiversity', grade: '6-8', ncert: ['EVS-7.1'], quiz: ['India forest cover goal?|33%|10%|50%|5%|0', 'Western Ghats are a?|Biodiversity hotspot|Desert|Glacier|City|0', 'Mangroves grow in?|Coastal waters|Mountains|Deserts|Plains|0', 'Deforestation causes?|Habitat loss|More trees|Better air|More rain|0', 'National tree of India?|Banyan|Neem|Mango|Teak|0'] },
    { title: 'Endangered Species of India', titleHi: 'भारत की लुप्तप्राय प्रजातियां', category: 'biodiversity', grade: '9-10', ncert: ['Bio-10.3'], quiz: ['Bengal tiger population?|~3000|100|50000|1 million|0', 'One-horned rhino is found in?|Assam|Delhi|Mumbai|Chennai|0', 'Project Tiger started in?|1973|2000|1950|2020|0', 'IUCN Red List tracks?|Threatened species|Weather|Soil|Water|0', 'Asiatic lion is found in?|Gujarat|Kerala|Bihar|UP|0'] },
    { title: 'Pollinators and Food Security', titleHi: 'परागणकर्ता और खाद्य सुरक्षा', category: 'biodiversity', grade: '9-10', ncert: ['Bio-10.4'], quiz: ['Main pollinators?|Bees|Fish|Snakes|Rocks|0', '% crops needing pollination?|75%|10%|1%|50%|0', 'Pesticides harm?|Pollinators|Nothing|Only weeds|Soil only|0', 'Honey bees produce?|Honey and wax|Metal|Plastic|Glass|0', 'Without pollinators?|Food shortage|More food|No change|Better crops|0'] },
    { title: 'Marine Biodiversity', titleHi: 'समुद्री जैव विविधता', category: 'biodiversity', grade: '11-12', ncert: ['Bio-12.5'], quiz: ['Coral reefs are called?|Rainforests of the sea|Deserts|Mountains|Plains|0', 'Ocean covers?|71% of Earth|10%|50%|90%|0', 'Plastic pollution kills?|Marine life|Nothing|Plants only|Soil|0', 'Whale sharks are?|Fish|Mammals|Birds|Reptiles|0', 'MPAs protect?|Marine habitats|Buildings|Roads|Farms|0'] },
    { title: 'Wetlands: Earth\'s Kidneys', titleHi: 'आर्द्रभूमि: पृथ्वी की किडनी', category: 'biodiversity', grade: '6-8', ncert: ['EVS-6.6'], quiz: ['Wetlands filter?|Water|Air|Sound|Light|0', 'Ramsar Convention protects?|Wetlands|Forests|Deserts|Mountains|0', 'India has how many Ramsar sites?|75+|5|10|200|0', 'Wetlands store?|Carbon|Metal|Plastic|Glass|0', 'Chilika Lake is in?|Odisha|Delhi|UP|Gujarat|0'] },
    { title: 'Invasive Species', titleHi: 'आक्रामक प्रजातियां', category: 'biodiversity', grade: '9-10', ncert: ['Bio-10.5'], quiz: ['Invasive species are?|Non-native harmful|All animals|Only plants|Helpful|0', 'Lantana in India is?|Invasive|Native|Helpful|Rare|0', 'Invasive species threaten?|Native biodiversity|Buildings|Weather|Nothing|0', 'Water hyacinth blocks?|Sunlight in water|Wind|Roads|Sound|0', 'Prevention is?|Best strategy|Useless|Expensive only|Impossible|0'] },
    { title: 'Sacred Groves of India', titleHi: 'भारत के पवित्र वन', category: 'biodiversity', grade: '11-12', ncert: ['Bio-12.6'], quiz: ['Sacred groves are?|Community-protected forests|Parks|Gardens|Farms|0', 'They conserve?|Biodiversity|Buildings|Roads|Machines|0', 'Dev Van means?|Sacred forest|City|River|Mountain|0', 'Found across?|All Indian states|Only Kerala|Only Rajasthan|Nowhere|0', 'Threats include?|Encroachment|More trees|Better protection|Rain|0'] },
    { title: 'Seed Banks and Crop Diversity', titleHi: 'बीज बैंक और फसल विविधता', category: 'biodiversity', grade: '11-12', ncert: ['Bio-12.7'], quiz: ['Seed banks store?|Genetic diversity|Money|Books|Tools|0', 'Svalbard vault is in?|Norway|India|USA|China|0', 'Monoculture risks?|Disease outbreak|Better yield|More diversity|Nothing|0', 'India\'s crop diversity is?|Very high|Very low|Zero|Average|0', 'Traditional seeds are?|Climate adapted|Artificial|Imported only|New|0'] },
    { title: 'Wildlife Photography Ethics', titleHi: 'वन्यजीव फोटोग्राफी नैतिकता', category: 'biodiversity', grade: '6-8', ncert: ['EVS-6.7'], quiz: ['Keep what distance from wildlife?|Safe distance|Very close|Touch them|Feed them|0', 'Flash photography can?|Disturb animals|Help them|Nothing|Heal them|0', 'Best time for wildlife photos?|Dawn/dusk|Midnight|Noon|Never|0', 'Feeding wildlife is?|Harmful|Always good|Required|Helpful|0', 'Report poaching to?|Forest department|Friends|No one|Social media only|0'] },
    // Water (10)
    { title: 'Water Cycle and Conservation', titleHi: 'जल चक्र और संरक्षण', category: 'water', grade: '6-8', ncert: ['EVS-6.8'], quiz: ['% of freshwater available?|Less than 1%|50%|75%|25%|0', 'Evaporation needs?|Heat|Cold|Darkness|Silence|0', 'Groundwater is stored in?|Aquifers|Clouds|Ocean|Ice|0', 'Rainwater harvesting collects?|Rainwater|Seawater|Sewage|Air|0', 'Water conservation means?|Using wisely|Wasting|Polluting|Ignoring|0'] },
    { title: 'River Pollution in India', titleHi: 'भारत में नदी प्रदूषण', category: 'water', grade: '9-10', ncert: ['Sci-10.17'], quiz: ['Most polluted river?|Yamuna|Amazon|Thames|Nile|0', 'Namami Gange is for?|Cleaning Ganga|Building dams|Fishing|Tourism|0', 'Sewage causes?|Eutrophication|Clear water|Better fish|Nothing|0', 'BOD measures?|Organic pollution|Temperature|Color|Smell|0', 'STPs treat?|Sewage|Clean water|Air|Soil|0'] },
    { title: 'Drip Irrigation and Smart Farming', titleHi: 'ड्रिप सिंचाई और स्मार्ट खेती', category: 'water', grade: '9-10', ncert: ['Sci-10.18'], quiz: ['Drip irrigation saves?|Water|Electricity only|Nothing|Soil|0', 'Agriculture uses what % of water?|~70%|10%|5%|50%|0', 'Mulching reduces?|Evaporation|Growth|Yield|Nothing|0', 'Smart farming uses?|Sensors and data|Guesswork|Magic|Nothing|0', 'Water footprint of rice vs wheat?|Rice is higher|Same|Wheat is higher|None use water|0'] },
    { title: 'Ocean Acidification', titleHi: 'समुद्र अम्लीकरण', category: 'water', grade: '11-12', ncert: ['Chem-12.5'], quiz: ['Ocean absorbs what % of CO2?|~30%|0%|100%|5%|0', 'pH decrease means?|More acidic|More basic|No change|Unknown|0', 'Affected most?|Shell-forming organisms|Land animals|Birds|Insects|0', 'Coral bleaching is from?|Temperature + acidity|Cold|Wind|Rain|0', 'Solution includes?|Reducing CO2 emissions|More fishing|Ignoring|Adding salt|0'] },
    { title: 'Groundwater Depletion', titleHi: 'भूजल का ह्रास', category: 'water', grade: '9-10', ncert: ['Geo-10.3'], quiz: ['India is the largest user of?|Groundwater|Solar energy|Wind|Nuclear|0', 'Punjab faces?|Water table decline|Flood|Excess water|None|0', 'Recharge means?|Replenishing aquifers|Emptying|Polluting|Heating|0', 'Check dams help?|Recharge groundwater|Block rivers|Cause floods|Nothing|0', 'Sustainable use means?|Not exceeding recharge|Using all|Wasting|Polluting|0'] },
    { title: 'Rainwater Harvesting at Home', titleHi: 'घर पर वर्षा जल संचयन', category: 'water', grade: '6-8', ncert: ['EVS-6.9'], quiz: ['Rooftop harvesting collects from?|Roof|Road|River|Sea|0', 'First flush diverts?|Dirty initial water|Clean water|Air|Nothing|0', 'Storage tank should be?|Covered|Open|Heated|Frozen|0', 'Filter removes?|Debris|Color|Smell|Sound|0', 'One mm rain on 100sqm roof = ?|100 liters|1 liter|1000 liters|10 liters|0'] },
    { title: 'Wetland Restoration', titleHi: 'आर्द्रभूमि पुनर्स्थापना', category: 'water', grade: '11-12', ncert: ['Geo-12.4'], quiz: ['Wetlands act as?|Natural sponges|Heaters|Deserts|Barriers|0', 'Restoration involves?|Removing invasives|Adding concrete|Draining|Paving|0', 'Benefits include?|Flood control|More pollution|Less biodiversity|Nothing|0', 'Community involvement is?|Essential|Unnecessary|Harmful|Optional|0', 'Success is measured by?|Species return|Building count|Road length|Population|0'] },
    { title: 'Virtual Water Trade', titleHi: 'वर्चुअल जल व्यापार', category: 'water', grade: '11-12', ncert: ['Geo-12.5'], quiz: ['Virtual water is?|Water used to produce goods|Visible water|Bottled water|Tap water|0', '1 kg beef needs?|~15000 liters|10 liters|100 liters|1 liter|0', '1 kg rice needs?|~2500 liters|5 liters|50 liters|500 liters|0', 'Water-rich countries export?|Virtual water in products|Actual rivers|Rain|Ice|0', 'Reducing meat consumption saves?|Significant water|No water|Very little|Nothing|0'] },
    { title: 'Water Quality Testing', titleHi: 'जल गुणवत्ता परीक्षण', category: 'water', grade: '6-8', ncert: ['EVS-7.2'], quiz: ['pH of pure water?|7|0|14|3|0', 'Turbidity measures?|Cloudiness|Temperature|Color|Taste|0', 'TDS stands for?|Total Dissolved Solids|Temperature|Taste|Toxicity|0', 'Safe drinking water TDS?|Below 500 ppm|Above 5000|Any|Zero|0', 'Boiling water kills?|Bacteria|Chemicals|Metals|Salt|0'] },
    { title: 'Floods and Disaster Preparedness', titleHi: 'बाढ़ और आपदा तैयारी', category: 'water', grade: '9-10', ncert: ['Geo-10.4'], quiz: ['Floods are caused by?|Heavy rainfall|Drought|Cold|Wind only|0', 'NDRF stands for?|National Disaster Response Force|Nothing|National Defense|Navy Dept|0', 'First aid kit should have?|Bandages and medicines|Only food|Only water|Nothing|0', 'Evacuation means?|Moving to safety|Staying put|Ignoring|Running blindly|0', 'Early warning helps?|Save lives|Nothing|Cause panic|Waste time|0'] },
    // Waste (10)
    { title: 'Segregation at Source', titleHi: 'स्रोत पर अलगाव', category: 'waste', grade: '6-8', ncert: ['EVS-6.10'], quiz: ['Green bin is for?|Wet waste|Dry waste|Hazardous|E-waste|0', 'Blue bin is for?|Dry waste|Wet waste|Medical|Organic|0', 'Segregation means?|Separating by type|Mixing|Burning|Dumping|0', 'Composting uses?|Wet waste|Plastic|Metal|Glass|0', 'Why segregate?|Enables recycling|No reason|Its law only|Fun|0'] },
    { title: 'Plastic Pollution Crisis', titleHi: 'प्लास्टिक प्रदूषण संकट', category: 'waste', grade: '9-10', ncert: ['Sci-10.19'], quiz: ['Plastic takes how long to decompose?|100+ years|1 day|1 week|1 month|0', 'Microplastics are?|Tiny plastic fragments|Big bottles|Clean water|Food|0', 'Single-use plastics include?|Straws and bags|Cars|Buildings|Furniture|0', 'India banned what thickness?|Below 75 micron|All plastic|None|Below 1mm|0', 'Best alternative?|Cloth bags|More plastic|Paper only|Nothing|0'] },
    { title: 'E-Waste Management', titleHi: 'ई-कचरा प्रबंधन', category: 'waste', grade: '9-10', ncert: ['Sci-10.20'], quiz: ['E-waste includes?|Old electronics|Food waste|Paper|Cloth|0', 'Hazardous elements in e-waste?|Lead and mercury|Water|Air|Soil|0', 'Proper disposal means?|Authorized recyclers|Burning|Dumping|Burying|0', 'India generates how much e-waste?|3+ million tonnes/year|100 kg|1 tonne|10 tonnes|0', 'Extended Producer Responsibility means?|Manufacturers handle disposal|Users ignore|Government only|Nobody|0'] },
    { title: 'Composting 101', titleHi: 'कम्पोस्टिंग 101', category: 'waste', grade: '6-8', ncert: ['EVS-7.3'], quiz: ['Composting breaks down?|Organic matter|Plastic|Metal|Glass|0', 'Good for compost?|Fruit peels|Plastic bags|Batteries|Paint|0', 'Compost improves?|Soil health|Pollution|Nothing|Air quality only|0', 'Time to make compost?|4-8 weeks|1 day|1 year|10 years|0', 'Worm composting uses?|Earthworms|Snakes|Fish|Birds|0'] },
    { title: 'Circular Economy', titleHi: 'चक्रीय अर्थव्यवस्था', category: 'waste', grade: '11-12', ncert: ['Eco-12.3'], quiz: ['Circular economy means?|Reuse and recycle|Use and throw|Linear production|Burn everything|0', 'Linear economy is?|Take-make-waste|Sustainable|Circular|Efficient|0', 'Upcycling means?|Creating higher value|Downgrading|Throwing away|Burning|0', 'Cradle to cradle means?|Products designed for reuse|Birth to death|Nothing|Linear|0', 'Best example?|Refurbished electronics|Single-use cups|Disposable plates|Plastic bags|0'] },
    { title: 'Biomedical Waste Handling', titleHi: 'जैव चिकित्सा कचरा प्रबंधन', category: 'waste', grade: '11-12', ncert: ['Bio-12.8'], quiz: ['Yellow bag is for?|Contaminated waste|Paper|Metal|Food|0', 'Sharps go in?|Puncture-proof container|Plastic bag|Open bin|Floor|0', 'Autoclaving uses?|Steam sterilization|Cold water|Air|Light|0', 'BMW Rules apply to?|Healthcare facilities|Only homes|Schools|Farms|0', 'Improper disposal causes?|Infections|Nothing|Better health|Clean water|0'] },
    { title: '3R: Reduce Reuse Recycle', titleHi: '3R: कम करो, पुन: उपयोग, रीसायकल', category: 'waste', grade: '6-8', ncert: ['EVS-6.11'], quiz: ['Most important R?|Reduce|Recycle|Reuse|None|0', 'Reusing a bottle is?|Reuse|Reduce|Recycle|Waste|0', 'Melting old glass for new is?|Recycling|Reducing|Reusing|Littering|0', 'Buying less packaging is?|Reducing|Recycling|Reusing|Ignoring|0', 'Best waste?|No waste|More waste|Mixed waste|Burned waste|0'] },
    { title: 'Zero Waste Schools', titleHi: 'शून्य कचरा विद्यालय', category: 'waste', grade: '9-10', ncert: ['EVS-9.1'], quiz: ['Zero waste aims for?|No landfill waste|Zero effort|Zero students|Zero teachers|0', 'Eco-clubs help by?|Leading waste projects|Doing nothing|Only studying|Playing|0', 'Paper recycling saves?|Trees|Nothing|Time only|Money only|0', 'Composting in school uses?|Kitchen waste|Books|Desks|Chairs|0', 'Audit means?|Measuring waste|Cleaning|Cooking|Ignoring|0'] },
    { title: 'Textile Waste and Fast Fashion', titleHi: 'कपड़ा कचरा और फास्ट फैशन', category: 'waste', grade: '11-12', ncert: ['Eco-12.4'], quiz: ['Fashion industry is which largest polluter?|2nd|1st|Last|Not a polluter|0', 'Fast fashion means?|Cheap disposable clothing|Expensive|Durable|Handmade|0', 'Textile waste in landfills?|Millions of tonnes|Zero|Very little|None|0', 'Sustainable fashion means?|Quality long-lasting clothes|Buying more|Cheapest option|Disposable|0', 'Best action?|Buy less, buy better|Buy more|Follow trends|Throw away|0'] },
    { title: 'Hazardous Waste Safety', titleHi: 'खतरनाक कचरा सुरक्षा', category: 'waste', grade: '9-10', ncert: ['Sci-10.21'], quiz: ['Batteries contain?|Heavy metals|Water|Air|Food|0', 'Paint cans are?|Hazardous waste|Regular waste|Recyclable|Organic|0', 'Proper disposal prevents?|Soil contamination|Nothing|More waste|Noise|0', 'Never mix?|Chemicals|Vegetables|Fruits|Water|0', 'Labels help identify?|Hazard type|Price only|Brand only|Nothing|0'] },
    // Energy (10)
    { title: 'Solar Energy Basics', titleHi: 'सौर ऊर्जा की मूल बातें', category: 'energy', grade: '6-8', ncert: ['Sci-6.12'], quiz: ['Solar panels convert?|Sunlight to electricity|Wind to heat|Water to gas|Sound to light|0', 'India gets abundant?|Sunshine|Snow|Rain|Cold|0', 'Solar water heater uses?|Sunlight|Gas|Coal|Wind|0', 'Advantage of solar?|No pollution|Expensive only|Works at night|Uses fuel|0', 'Solar cells are made of?|Silicon|Wood|Paper|Cloth|0'] },
    { title: 'Energy at Home Audit', titleHi: 'घर पर ऊर्जा ऑडिट', category: 'energy', grade: '6-8', ncert: ['EVS-6.13'], quiz: ['Biggest home energy user?|AC/Heating|Lights|Fan|Clock|0', 'LED saves how much vs incandescent?|~80%|10%|1%|50%|0', 'Star rating means?|Energy efficiency|Color|Size|Weight|0', 'Standby power is?|Phantom load|Free|Zero|Helpful|0', 'Save energy by?|Turning off unused|Leaving on|Using more|Ignoring|0'] },
    { title: 'Wind and Hydro Power', titleHi: 'पवन और जल विद्युत', category: 'energy', grade: '9-10', ncert: ['Sci-10.22'], quiz: ['Wind farms are located?|Windy areas|Underground|Underwater|In cities|0', 'Turbine converts?|Kinetic to electrical|Heat to cold|Light to sound|None|0', 'Hydropower uses?|Falling water|Rising water|Still water|No water|0', 'Largest dam in India?|Tehri|Bhakra|Hirakud|Nagarjuna|0', 'Renewable means?|Naturally replenished|Used once|Finite|Artificial|0'] },
    { title: 'Nuclear Energy: Pros and Cons', titleHi: 'परमाणु ऊर्जा: फायदे और नुकसान', category: 'energy', grade: '11-12', ncert: ['Phy-12.13'], quiz: ['Nuclear energy uses?|Uranium/Thorium|Coal|Oil|Gas|0', 'India has thorium reserves?|Yes large|No|Very little|Unknown|0', 'Main concern?|Radioactive waste|Noise|Smell|Cost only|0', 'Nuclear provides base?|Load power|Peak only|Nothing|Variable|0', 'Fusion is?|Combining atoms|Splitting atoms|Burning|Cooling|0'] },
    { title: 'Energy Conservation Act', titleHi: 'ऊर्जा संरक्षण अधिनियम', category: 'energy', grade: '11-12', ncert: ['Eco-12.5'], quiz: ['BEE stands for?|Bureau of Energy Efficiency|Board of Education|Bureau of Environment|Bank of Energy|0', 'Star labeling is?|Energy rating|Color coding|Price tag|Size label|0', 'PAT scheme targets?|Industrial energy efficiency|Pollution|Waste|Water|0', 'Energy audit identifies?|Savings opportunities|Problems only|Nothing|Costs|0', 'LED Street Lights|Save 50%+ energy|Use more|Same|Increase cost|0'] },
    { title: 'Biofuels and Biogas', titleHi: 'जैव ईंधन और बायोगैस', category: 'energy', grade: '9-10', ncert: ['Sci-10.23'], quiz: ['Biogas is produced from?|Organic waste|Plastic|Metal|Glass|0', 'Main gas in biogas?|Methane|Oxygen|Nitrogen|CO2|0', 'Biogas plant uses?|Anaerobic digestion|Burning|Freezing|Drying|0', 'Ethanol is made from?|Sugarcane/corn|Petroleum|Coal|Sand|0', 'Biofuels are?|Renewable|Fossil|Nuclear|Mineral|0'] },
    { title: 'Smart Grids', titleHi: 'स्मार्ट ग्रिड', category: 'energy', grade: '11-12', ncert: ['Phy-12.14'], quiz: ['Smart grid uses?|Digital technology|Paper|Manual controls|Nothing|0', 'Net metering allows?|Selling excess solar|Free electricity|Unlimited use|Nothing|0', 'Peak demand is?|Highest usage time|Lowest|Average|Zero|0', 'Smart meters show?|Real-time consumption|Only monthly|Nothing|Weather|0', 'Grid modernization helps?|Integrate renewables|Add coal|Remove solar|Nothing|0'] },
    { title: 'Hydrogen Economy', titleHi: 'हाइड्रोजन अर्थव्यवस्था', category: 'energy', grade: '11-12', ncert: ['Chem-12.6'], quiz: ['Green hydrogen uses?|Renewable electricity|Coal|Oil|Gas|0', 'Hydrogen fuel cell produces?|Electricity and water|Pollution|CO2|Noise|0', 'India H2 mission target?|5 MMT by 2030|None|100 MMT|1 MMT|0', 'Challenge is?|Storage and transport|Color|Smell|Sound|0', 'Ammonia can carry?|Hydrogen|Electricity|Heat|Light|0'] },
    { title: 'Energy Poverty in India', titleHi: 'भारत में ऊर्जा गरीबी', category: 'energy', grade: '9-10', ncert: ['Eco-10.2'], quiz: ['Energy poverty means?|Lack of modern energy|Too much energy|Free energy|None|0', 'Saubhagya scheme provides?|Electricity connections|Water|Food|Housing|0', 'Clean cooking fuel is?|LPG/electricity|Wood|Dung|Coal|0', 'Indoor air pollution from?|Biomass burning|AC|Fan|LED|0', 'Access to energy improves?|Education and health|Nothing|Pollution|Waste|0'] },
    { title: 'Energy Storage Revolution', titleHi: 'ऊर्जा भंडारण क्रांति', category: 'energy', grade: '11-12', ncert: ['Phy-12.15'], quiz: ['Lithium-ion batteries are used in?|EVs and phones|Only toys|Only watches|Nothing|0', 'Pumped hydro stores?|Energy as water|Heat|Light|Sound|0', 'Battery recycling is?|Essential|Unnecessary|Harmful|Impossible|0', 'Solid-state batteries are?|Next generation|Old technology|Liquid|Gas|0', 'Gravity storage uses?|Lifting weights|Burning fuel|Flowing water|Wind|0'] },
];

async function seed() {
    console.log('🌱 Seeding 50 Content Items...\n');
    await mongoose.connect(MONGO_URI);

    const ContentItem = require('../models/ContentItem');

    let created = 0;
    let skipped = 0;

    for (const lesson of lessons) {
        const existing = await ContentItem.findOne({ title: lesson.title });
        if (existing) { skipped++; continue; }

        const quizQuestions = lesson.quiz.map(q => {
            const parts = q.split('|');
            return {
                question: parts[0],
                options: parts.slice(1, 5),
                correctIndex: parseInt(parts[5]),
            };
        });

        await ContentItem.create({
            title: lesson.title,
            titleHi: lesson.titleHi,
            category: lesson.category,
            type: 'lesson',
            status: 'published',
            gradeLevel: [lesson.grade],
            ncertAlignmentTags: lesson.ncert,
            body: `# ${lesson.title}\n\nThis lesson covers key concepts about ${lesson.category} and environmental sustainability. Students will learn through interactive content and complete a quiz to test their understanding.\n\n## Learning Objectives\n- Understand fundamental concepts of ${lesson.category}\n- Connect theory to real-world environmental challenges in India\n- Identify actionable steps students can take\n\n## Activity Suggestion\nAfter completing this lesson, try a related eco-activity and submit evidence for eco-points!`,
            quiz: quizQuestions,
            coverImage: `https://source.unsplash.com/800x400/?${lesson.category},environment,india`,
        });
        created++;
        process.stdout.write(`  ✅ ${created}/50 ${lesson.title}\r`);
    }

    console.log(`\n\n📊 Results: ${created} created, ${skipped} skipped`);
    await mongoose.disconnect();
    process.exit(0);
}

seed().catch(err => { console.error('Fatal:', err.message); process.exit(1); });
